//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageHandler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StorageHandler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Str_NewCategory { get { return ResourceManager.GetString("Str_NewCategory", resourceCulture); } }
        public static string Str_SearchPlaceholder { get { return ResourceManager.GetString("Str_SearchPlaceholder", resourceCulture); } }
        public static string Str_Undo { get { return ResourceManager.GetString("Str_Undo", resourceCulture); } }
        public static string Str_Save { get { return ResourceManager.GetString("Str_Save", resourceCulture); } }
        public static string Str_Revert { get { return ResourceManager.GetString("Str_Revert", resourceCulture); } }
        public static string Str_CloseApp { get { return ResourceManager.GetString("Str_CloseApp", resourceCulture); } }
        public static string Str_Minimize { get { return ResourceManager.GetString("Str_Minimize", resourceCulture); } }
        public static string Str_Maximize { get { return ResourceManager.GetString("Str_Maximize", resourceCulture); } }
        public static string Str_Restore { get { return ResourceManager.GetString("Str_Restore", resourceCulture); } }
        public static string Str_Settings { get { return ResourceManager.GetString("Str_Settings", resourceCulture); } }
        public static string Str_Qty { get { return ResourceManager.GetString("Str_Qty", resourceCulture); } }
        public static string Str_Description { get { return ResourceManager.GetString("Str_Description", resourceCulture); } }
        public static string Str_AddItem { get { return ResourceManager.GetString("Str_AddItem", resourceCulture); } }
        public static string Str_DeleteItem { get { return ResourceManager.GetString("Str_DeleteItem", resourceCulture); } }
        public static string Str_AddBox { get { return ResourceManager.GetString("Str_AddBox", resourceCulture); } }
        public static string Str_DeleteBox { get { return ResourceManager.GetString("Str_DeleteBox", resourceCulture); } }
        public static string Str_NavigateUp { get { return ResourceManager.GetString("Str_NavigateUp", resourceCulture); } }
        public static string Str_NavigateInto { get { return ResourceManager.GetString("Str_NavigateInto", resourceCulture); } }
        public static string Str_ConvertToItemList { get { return ResourceManager.GetString("Str_ConvertToItemList", resourceCulture); } }
        public static string Str_Error { get { return ResourceManager.GetString("Str_Error", resourceCulture); } }
        public static string Str_UnsavedChangesTitle { get { return ResourceManager.GetString("Str_UnsavedChangesTitle", resourceCulture); } }
        public static string Str_UnsavedChangesMsg { get { return ResourceManager.GetString("Str_UnsavedChangesMsg", resourceCulture); } }
        public static string Str_ConfirmUndoTitle { get { return ResourceManager.GetString("Str_ConfirmUndoTitle", resourceCulture); } }
        public static string Str_ConfirmUndoMsg { get { return ResourceManager.GetString("Str_ConfirmUndoMsg", resourceCulture); } }
        public static string Str_InvalidOp { get { return ResourceManager.GetString("Str_InvalidOp", resourceCulture); } }
        public static string Str_BoxInItemListError { get { return ResourceManager.GetString("Str_BoxInItemListError", resourceCulture); } }
        public static string Str_MergeTitle { get { return ResourceManager.GetString("Str_MergeTitle", resourceCulture); } }
        public static string Str_MergeMsg { get { return ResourceManager.GetString("Str_MergeMsg", resourceCulture); } }
        public static string Str_DeleteCategory { get { return ResourceManager.GetString("Str_DeleteCategory", resourceCulture); } }
        public static string Str_ConfirmDeleteCategory { get { return ResourceManager.GetString("Str_ConfirmDeleteCategory", resourceCulture); } }
        public static string Str_CategoryExists { get { return ResourceManager.GetString("Str_CategoryExists", resourceCulture); } }
        public static string Str_EnterCategoryName { get { return ResourceManager.GetString("Str_EnterCategoryName", resourceCulture); } }
        public static string Str_BoxStructureUpdated { get { return ResourceManager.GetString("Str_BoxStructureUpdated", resourceCulture); } }
        public static string Str_BoxChildSuccess { get { return ResourceManager.GetString("Str_BoxChildSuccess", resourceCulture); } }
        public static string Str_CircularRefError { get { return ResourceManager.GetString("Str_CircularRefError", resourceCulture); } }
        public static string Str_MakeChildBoxTitle { get { return ResourceManager.GetString("Str_MakeChildBoxTitle", resourceCulture); } }
        public static string Str_MakeChildBoxMsg { get { return ResourceManager.GetString("Str_MakeChildBoxMsg", resourceCulture); } }
        public static string Str_MakeChildBoxMsgDetails { get { return ResourceManager.GetString("Str_MakeChildBoxMsgDetails", resourceCulture); } }
        public static string Str_SettingsNotImplemented { get { return ResourceManager.GetString("Str_SettingsNotImplemented", resourceCulture); } }
        public static string Str_SaveSuccess { get { return ResourceManager.GetString("Str_SaveSuccess", resourceCulture); } }
        public static string Str_LinkError { get { return ResourceManager.GetString("Str_LinkError", resourceCulture); } }
        public static string Str_NoDataToSave { get { return ResourceManager.GetString("Str_NoDataToSave", resourceCulture); } }
        public static string Str_MergeError { get { return ResourceManager.GetString("Str_MergeError", resourceCulture); } }
        public static string Str_Box { get { return ResourceManager.GetString("Str_Box", resourceCulture); } }
        public static string Str_ItemList { get { return ResourceManager.GetString("Str_ItemList", resourceCulture); } }
        public static string Str_Cancel { get { return ResourceManager.GetString("Str_Cancel", resourceCulture); } }
        public static string Str_OK { get { return ResourceManager.GetString("Str_OK", resourceCulture); } }
        public static string Str_SelectComponent { get { return ResourceManager.GetString("Str_SelectComponent", resourceCulture); } }
        public static string Str_Filters { get { return ResourceManager.GetString("Str_Filters", resourceCulture); } }
        public static string Str_ManageCategories { get { return ResourceManager.GetString("Str_ManageCategories", resourceCulture); } }
        public static string Str_CreateNewModel { get { return ResourceManager.GetString("Str_CreateNewModel", resourceCulture); } }
        public static string Str_SearchModelPlaceholder { get { return ResourceManager.GetString("Str_SearchModelPlaceholder", resourceCulture); } }
        public static string Str_Add { get { return ResourceManager.GetString("Str_Add", resourceCulture); } }
        public static string Str_ComponentCategory { get { return ResourceManager.GetString("Str_ComponentCategory", resourceCulture); } }
        public static string Str_ModelNumberPrompt { get { return ResourceManager.GetString("Str_ModelNumberPrompt", resourceCulture); } }
        public static string Str_DatasheetPrompt { get { return ResourceManager.GetString("Str_DatasheetPrompt", resourceCulture); } }
        public static string Str_TypePrompt { get { return ResourceManager.GetString("Str_TypePrompt", resourceCulture); } }
        public static string Str_ValuePrompt { get { return ResourceManager.GetString("Str_ValuePrompt", resourceCulture); } }
        public static string Str_Create { get { return ResourceManager.GetString("Str_Create", resourceCulture); } }
        public static string Str_ModelExists { get { return ResourceManager.GetString("Str_ModelExists", resourceCulture); } }
        public static string Str_ConfirmDeleteModel { get { return ResourceManager.GetString("Str_ConfirmDeleteModel", resourceCulture); } }
        public static string Str_InvalidQty { get { return ResourceManager.GetString("Str_InvalidQty", resourceCulture); } }
        public static string Str_InvalidQtyTitle { get { return ResourceManager.GetString("Str_InvalidQtyTitle", resourceCulture); } }
        public static string Str_SelectModelMsg { get { return ResourceManager.GetString("Str_SelectModelMsg", resourceCulture); } }
        public static string Str_SelectionRequired { get { return ResourceManager.GetString("Str_SelectionRequired", resourceCulture); } }
        public static string Str_EnterModelNumber { get { return ResourceManager.GetString("Str_EnterModelNumber", resourceCulture); } }
        public static string Str_ValidationError { get { return ResourceManager.GetString("Str_ValidationError", resourceCulture); } }
        public static string Str_SelectCategoryMsg { get { return ResourceManager.GetString("Str_SelectCategoryMsg", resourceCulture); } }
        public static string Str_InvalidComponent { get { return ResourceManager.GetString("Str_InvalidComponent", resourceCulture); } }
        public static string Str_DeleteSelected { get { return ResourceManager.GetString("Str_DeleteSelected", resourceCulture); } }
        public static string Str_ImportCommonCategories { get { return ResourceManager.GetString("Str_ImportCommonCategories", resourceCulture); } }
        public static string Str_Close { get { return ResourceManager.GetString("Str_Close", resourceCulture); } }
        public static string Str_ConfirmDeleteCategorySimple { get { return ResourceManager.GetString("Str_ConfirmDeleteCategorySimple", resourceCulture); } }
        public static string Str_ImportCategoriesSuccess { get { return ResourceManager.GetString("Str_ImportCategoriesSuccess", resourceCulture); } }
        public static string Str_ItemsDatabaseFile { get { return ResourceManager.GetString("Str_ItemsDatabaseFile", resourceCulture); } }
    }
}
